-- Table: public.topics

-- DROP TABLE IF EXISTS public.topics;

CREATE TABLE IF NOT EXISTS public.topics
(
    topic_id bigint primary key generated by default as identity,
    topic_name text COLLATE pg_catalog."default",
    frequency integer DEFAULT 10,
    last_tried date,
    last_success date
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.topics
    OWNER to ollie;


-- Table: public.questionbank

-- DROP TABLE IF EXISTS public.questionbank;

CREATE TABLE IF NOT EXISTS public.questionbank
(
    id bigint NOT NULL primary key generated by default as identity,
    parent_id integer,
    topic_id integer NOT NULL,
    question text COLLATE pg_catalog."default",
    answer text COLLATE pg_catalog."default",
    CONSTRAINT "question-topic-pairing" FOREIGN KEY (topic_id)
        REFERENCES public.topics (topic_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.questionbank
    OWNER to ollie;


 -- Table: public.answers

-- DROP TABLE IF EXISTS public.answers;

CREATE TABLE IF NOT EXISTS public.answers
(
    answer_id bigint NOT NULL primary key generated by default as identity,
    topic_id integer NOT NULL,
    success boolean NOT NULL,
    answers text COLLATE pg_catalog."default",
    date date,
    CONSTRAINT answers_topic_id_fkey FOREIGN KEY (topic_id)
        REFERENCES public.topics (topic_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.answers
    OWNER to ollie;